# Site
repository: anukritiw/resume-theme
favicon: images/favicon.ico

# Personal info
name: Anu Kriti Wadhwa
title: Student | BComp (Computer Science) + University Scholars' Programme (USP)
university: National University of Singapore (NUS), School of Computing (SoC)
email: anu.kriti.wadhwa@u.nus.edu
website: anukritiw.github.io

# Social links
# twitter_username: facespics
github_username:  anukritiw
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: anukritiw
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Anu and I'm a year 2 student studying Computer Science at the School of Computing(SoC) at the National University of Singapore (NUS). I am also studying in a parallel academic programme, the University Scholars' Programme (USP) at NUS.

  I intend to focus in Computer Graphics, Artificial Intelligence and Information Retrieval. I also have experience film-making and theatre productions.

  The things that I currently have the most experience working with are
  <mark>Java</mark>,
  <mark>C++</mark>,
  <mark>OpenGL</mark> and
  <mark>JavaScript</mark>.

  I also have experience with
  <mark>Film and Stage Direction</mark>,
  <mark>Screenwriting and Playwriting</mark>,
  <mark>Post-production for film</mark> and
  <mark>Stage Management</mark>.

  Currently, during the longer winter break from school, I have set out to pick up <mark>Maya</mark> and <mark>Houdini</mark>.

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

#Portfolio Section
# portfolio_title: Portfolio

# More Section
more_title: In my spare time
more_content: | # this will include new lines to allow paragraphs
  Watching reruns of *Gilmore Girls* and *Friends* are an absolute must. *Legally Blonde* and *Toy Story* are my other guilty pleasures. Spotify is also a daily essential! Without it, days would be too quiet.

  I crave adventure. Usually, adventure takes the form of travel, and I am lucky to have had the opportunity to visit places such as Boston, Paris, London, Thailand, India, China, Australia, etc. and I hope that I find myself embarking on more similar grand adventures.
  Mini-adventures within Singapore are also refreshing escapes from the ordinary. Doses of spontaneity are imperitive. :)
# Footer
footer_show_references: true

# Build settings
remote_theme: anukritiw/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
