# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Anu Kriti Wadhwa
title: Student
email: anu.kriti.wadhwa@u.nus.edu
website: anukritiw.github.io

# Social links
# twitter_username: facespics
github_username:  anukritiw
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: anukritiw
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Anu and I'm a year 2 student studying Computer Science at the School of Computing(SoC) at the National University of Singapore (NUS). I am also studying in a parallel academic programme, the University Scholars' Programme (USP) at NUS.

  I intend to focus in Computer Graphics, Artificial Intelligence and Information Retrieval. I also have experience film-making and theatre productions.

  The things that I currently have the most experience working with are
  <mark>Java</mark>,
  <mark>C++</mark>,
  <mark>OpenGL</mark> and
  <mark>JavaScript</mark>.

  I also have experience with
  <mark>Film and Stage Direction</mark>,
  <mark>Screenwriting and Playwriting</mark>,
  <mark>Post-production for film</mark> and
  <mark>Stage Management</mark>.

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

#Portfolio Section
# portfolio_title: Portfolio

# More Section
more_title: When I'm not Programming
more_content: | # this will include new lines to allow paragraphs
  When I'm not in classes, or working on any school film or theatre productions,
  I enjoy watching films at local film festivals, or even just in my room on Netlix.
  I also enjoy listening to music and playing the drums. During longer breaks, I try
  to attend courses and workshops (e.g. courses in DJing, workshop for colour grading, etc.).

# Footer
footer_show_references: true

# Build settings
remote_theme: anukritiw/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
